AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Reset Password
Resources:
  PasswordReset:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: .
      Description: Reset Password
      MemorySize: 128
      Timeout: 90
      Role: 'arn:aws:iam::475971158259:role/LamdaExecution'
      Tags:
        'lambda-console:blueprint': lex-make-appointment
